### ISSUE TITLE
Simplify project setup.

### ISSUE THREAD

**Issue by jwaggs** [CryptoCaddy/web-app#22]
##### Description
Currently the project requires a host of env variables and a firebase credentials file to work properly. This is a huge deterrent to developers just getting started with the project. We need to discuss and implement a solution that will alleviate this headache.

**Comment by naeramarth7** [comment]
Some input about the env vars part:

### Option 1: Default values in docker-compose.yml
For some of the env variables, it might be an option to set defaults some defaults in the `docker-compose.yml`.

Pros:
* Defaults that are overwritten by env vars

Cons:
* redundant, need to be updated for every service

### Option 2: `.env` file
Docker `docker-compose` does also work with an `.env` file in the *current working directory*. It automatically evaluates the env vars from there when running `docker-compose` (see [docs](https://docs.docker.com/compose/env-file/))

Pro:
* single file to manage env vars
* overwritten with system env vars

Cons:
* does only work if it's in the current working directory (if you're like me, you'll never be in the root folder of this project)
* it's best practice to gitignore the `.env` file / folder.

### Option 3: `env_file` option
Environment files can also be provided with a [`env_file`](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option) option.

Pros:
* single file (or multiple files) to manage env vars
* independent of current working directory
* overwritten with system env vars

Cons:
* ...

### Option 4: autoenv
I myself use [autoenv](https://github.com/kennethreitz/autoenv) to source parent `.env` files.

Pros:
* Same as option 2 without the "current working directory" con

Cons:
* to complex for a "simple setup"

**Comment by jwaggs** [comment]
For option 3... were the lack of cons due to the fact that there don't appear to be any?
